#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := derobin
EXCLUDE_COMPONENTS := aws_iot AzureIoT

include $(IDF_PATH)/make/project.mk

